/**
 * The CSV download, built in the browser.
 *
 * It used to be /api/export.csv, generated by the Worker from D1 over whatever
 * filters were live. D1 is gone; the unfiltered file is published as
 * /data/export.csv, and a FILTERED download is assembled here from the rows the
 * page is already showing.
 *
 * THIS IS A BYTE CONTRACT, not a convenience. The twelve columns are the
 * brief's deliverable, and somebody diffs one month's file against the last.
 * Three details each exist because getting them wrong broke something real:
 *
 *   - A UTF-8 BOM. Without it Excel reads the file as the local codepage and
 *     mangles every Chinese company name.
 *   - CRLF line endings, matching the Worker's writer.
 *   - Numbers formatted the way JavaScript's String() does it, which is where
 *     the Python exporter had to add _js_number: Python writes an integral
 *     float as "17.0" and JavaScript writes "17". Caught on 6147 / 2026-01,
 *     where yoy_acceleration_ppt differed between the two implementations for
 *     that reason alone and made every such column churn month to month.
 *
 * Column ORDER comes from the row object, which comes from the analytics view -
 * the brief's twelve columns in the specified order. Nothing here names them
 * except as the header for an empty result, which is what keeps the contract
 * intact when the view changes.
 */

import type { AnalyticsRow } from "./types";

/** The header for an EMPTY result only. With rows, the keys decide. */
const FALLBACK_COLUMNS = [
  "ticker", "company_name", "bucket", "tier", "month",
  "revenue_twd_thousands", "mom_pct", "yoy_pct", "prior_month_yoy_pct",
  "yoy_acceleration_ppt", "cumulative_ytd_revenue_twd_thousands",
  "cumulative_yoy_pct",
];

/** Quote only when the value contains a comma, a quote or a newline, and double
 *  an inner quote. QUOTE_MINIMAL, matching the Worker's csvCell(). */
export function csvCell(value: unknown): string {
  if (value === null || value === undefined) return "";
  const s = String(value);
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function toCsv(rows: readonly AnalyticsRow[]): string {
  const first = rows[0];
  const columns = first ? Object.keys(first) : FALLBACK_COLUMNS;
  const lines = [columns.map(csvCell).join(",")];
  for (const row of rows) {
    const cells = row as unknown as Record<string, unknown>;
    lines.push(columns.map((c) => csvCell(cells[c])).join(","));
  }
  // Trailing CRLF: the writer terminates every row, including the last.
  return "﻿" + lines.join("\r\n") + "\r\n";
}

/** A blob URL for `rows`. The caller must revoke it when the link goes away,
 *  or every filter change leaks a copy of the dataset for the life of the tab. */
export function csvObjectUrl(rows: readonly AnalyticsRow[]): string {
  return URL.createObjectURL(
    new Blob([toCsv(rows)], { type: "text/csv;charset=utf-8" }),
  );
}
